### ISSUE TITLE
Fix the metadata on 5 year aggregation

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/comt_2#1]
@marjy, can you (or someone familiar with the simulation) please go to this link:
https://github.com/ioos/comt_2/blob/master/cb_hypoxia/VIMS_CHesROMS-ECB/5year/test.yaml
and then click the pen icon (screen grab below) and edit the metadata for this simulation?:

When you are done editing, click the link at the bottom to submit a pull request. 

I purposely cut-and-pasted a summary from a different simulation so that you will want to fix it!

Tough love!  :smiley_cat: 

![7-22-2015 4-06-17 pm](https://cloud.githubusercontent.com/assets/1872600/8835958/c14a45d4-308b-11e5-9733-ff47c2d9ba57.png)

**Comment by marjy** [comment]
You bet! I edited it as you mentioned.

I did get a message saying that I was editing a project that I don’t have write access to. Apparently they’ve created a fork of this project for me to commit my proposed changes to. I’m not sure what it means when it says: “Submitting a change to this file will write it to a new branch in your fork, so you can send a pull request”?

But I tried!

I also changed “NSF” to “NASA” under acknowledgments, since NASA provided the funding for the model development.

Marjy

On Jul 22, 2015, at 4:05 PM, Rich Signell <notifications@github.com<mailto:notifications@github.com>> wrote:

@marjyhttps://github.com/marjy, can you please click the pen icon and edit this file:
https://github.com/ioos/comt_2/blob/master/cb_hypoxia/VIMS_CHesROMS-ECB/5year/test.yaml
When you are done editing, click the link at the bottom to submit a pull request.

I purposely cut-and-pasted a summary from a different simulation so that you will want to fix it!

Tough love! [:smiley_cat:]
